// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package mysql

import (
	"database/sql"
)

type User struct {
	ID        string
	Name      string
	Email     string
	CreatedAt sql.NullTime
}
